name: leaderboard

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Update Traffic'
        default: 'Update'
        required: true

jobs:
  leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Hackathon'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: 'Get Current UTC Time'
        run: echo "COMMIT_DATE=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: 'Generate Leaderboard'
        run: bash scripts/generate-leaderboard.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: 'Update README.md'
        run: bash scripts/update-readme.sh
      - name: 'Commit Changes'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Hackathon Update: ${{ env.COMMIT_DATE }}"
          branch: main
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

