name: Install Mush

on:
  push:
    branches:
      - main

env:
  HACKATHON_PACKAGE_NAME: console

jobs:
  install-mush:
    runs-on: ubuntu-latest
    steps:
      - name: Install Mush
        run: curl -fsSL https://get.javanile.org/mush | sh 
             && mkdir -p ~/.local/bin/ && cp ~/.mush/bin/mush ~/.local/bin/

      - name: Verify Mush installation
        run: mush --version

      - name: Install Hackathon package
        run: mush install ${HACKATHON_PACKAGE_NAME}
